question_list = [
    {"question_0": "Serial Correlation is a common problem in time-series data",
        "answer_0": "True",
        "question_1": "Serial Correlation is a common problem in cross-section data",
        "answer_1": "False"},
    {"question_0": "Standard error is obtained through dividing the standard deviation by square root of the sample size",
        "answer_0": "True",
        "question_1": "Standard deviation is the same as standard error",
        "answer_1": "False"},
    {"question_0": "Serial correlation is the same as autocorrelation",
        "answer_0": "True",
        "question_1": "Serial correlation problem occurs when independent variables are autocorrelated",
        "answer_1": "False"},
    {"question_0": "Logit is used when we have a binary dependent variable",
        "answer_0": "True",
        "question_1": "Logit is used when we have a dummy independent variable",
        "answer_1": "False"},
    {"question_0": "In OLS, the direction of causality is from the independent variable to the dependent variable",
     "answer_0": "True",
        "question_1": "In OLS, the direction of causality is from the dependent variable to the independent variable",
        "answer_1": "False"},
    {"question_0": "Independent and explanatory variables refer to the same thing",
        "answer_0": "True",
        "question_1": "Independent and outcome variables refer to the same thing",
        "answer_1": "False"},
    {"question_0": "In an autoregressive model, the lagged dependent variable is included in the independent variable list",
        "answer_0": "True",
        "question_1": "In an autoregressive model, the lagged independent variable is included as a dependent variable",
        "answer_1": "False"},
    {"question_0": "In statistical testing, null hypothesis is rejected when p-value is less than significance level",
        "answer_0": "True",
        "question_1": "In statistical testing, null hypothesis is rejected when p-value is higher than significance level",
        "answer_1": "False"},
    {"question_0": "One minus significance level gives the confidence level",
        "answer_0": "True",
        "question_1": "Confidence level is the same thing as the significance level",
        "answer_1": "False"},
    {"question_0": "Two-stage Least Squares is another name used for Instrumental Variable Estimation",
     "answer_0": "True",
        "question_1": "Instrumental Variable Estimation is another name given to Maximum Likelihood Estimation",
        "answer_1": "False"},
    {"question_0": "Logit and Probit model coefficient estimates are obtained by Maximum Likelihood estimation",
        "answer_0": "True",
        "question_1": "Logit and Probit model coefficient estimates are obtained by Ordinary Least Squares",
        "answer_1": "False"},
]
